### ISSUE TITLE
baRulho still uses deprecated functions from warbleR

### ISSUE THREAD

**Issue by maelle** [maRce10/baRulho#20]
On https://ropensci.r-universe.dev/builds#builds we see for instance

> Error: 'try_na' is not an exported object from 'namespace:warbleR'

> Quitting from lines 416-421 [unnamed-chunk-12] (align_test_sounds.Rmd)
Error: processing vignette 'align_test_sounds.Rmd' failed with diagnostics:
'try_na' is not an exported object from 'namespace:warbleR'

Since you maintain both packages you know more than me about the context and might even already be aware of that. :smile_cat:

**Comment by maRce10** [comment]
thanks!  it should be fixed now

**Comment by maelle** [comment]
Indeed, all green, thank you :tada:
